### ISSUE TITLE
Let's tag our first release! 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extension-workshop#107]
@bqbn, I'm not sure how tagged releases work, but I'd love to cut our first tag and deploy to production. Could you advise on next steps? 

/cc @mconca & @muffinresearch

**Comment by muffinresearch** [comment]
Assuming everything looks good on stage...

Based on the conventions we use for libs we'd typically try and match the version of the package.json.  Since that's already 1.0.0 it's possible to make the tag without any other changes from here: https://github.com/mozilla/extension-workshop/releases/new

Tag version can be `1.0.0`
Release title can match the tag `1.0.0`
Description can say anything you want.

Leave the draft part unchecked - that should do the first release once circle-ci has run.

**Comment by caitmuenster** [comment]
Thanks @muffinresearch! Do we need to attach any binaries?

**Comment by muffinresearch** [comment]
> Thanks @muffinresearch! Do we need to attach any binaries?

No, you can ignore that bit 👍

**Comment by caitmuenster** [comment]
👍 Ok -- just tagged [release 1.0.0](https://github.com/mozilla/extension-workshop/releases/tag/1.0.0). 🤞🏽

**Comment by muffinresearch** [comment]
@bqbn, I'm not sure if circle is backed up, but the tag doesn't seem to be getting deployed as yet.

**Comment by bqbn** [comment]
@caitmuenster @muffinresearch 

Per https://github.com/mozilla/extension-workshop/blob/master/.circleci/config.yml#L91, the release tag needs to have a letter `v` prefix.

We can either change that to not require `v`, or always use `v` prefix when we tag. Either way works for me.

**Comment by caitmuenster** [comment]
Thanks @bqbn! I just updated the release to be `v1.0.0` - is that correct? Do we need to update the other tags to have the `v` prefix as well?

**Comment by bqbn** [comment]
@caitmuenster actually, I think the problem is different. The regex on https://github.com/mozilla/extension-workshop/blob/master/.circleci/config.yml#L91 matches with or without letter `v`.

Reading the docs again, I see that it says,

> CircleCI does not run workflows for tags unless you explicitly specify tag filters. Additionally, if a job requires any other jobs (directly or indirectly), you must specify tag filters for those jobs.

So we need add a tag filter for the `build` job, because the `deploy` job depends on it.

I'll file a PR to fix it.
