### ISSUE TITLE
De-duplicate titles of tag pages 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/extension-workshop#583]
Right now, all tag pages (like https://extensionworkshop.com/tags/?q=WebExtensions and https://extensionworkshop.com/tags/?q=publish) have the same title, "Tags | Extension Workshop."

![Screen Shot 2020-03-09 at 10 13 56 AM](https://user-images.githubusercontent.com/23342476/76239386-b7ae8500-61ee-11ea-9f24-a554b84d03d4.png)

We should set the tag in the title, like, "Permissions | Tags | Extension Workshop" or "Publish | Tags | Extension Workshop." 

@muffinresearch, could you advise on how to fix this?

**Comment by muffinresearch** [comment]
This is similar to the problem here https://github.com/mozilla/extension-workshop/issues/567

We shouldn't be using the search for tags at all, I think this is something that will need a pretty in-depth refactor to achieve. Moving off Jekyll might provide a good opportunity for example, at least it's probably not worth attempting this before then unless it doesn't happen.

**Comment by muffinresearch** [comment]
This will be fixed by #654

**Comment by muffinresearch** [comment]
Fixed as part of the 11ty build now on -dev.
