### ISSUE TITLE
cloudfront invalidation failing

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/extension-workshop#64]
Getting the following error on deploys: 

```
Waiter InvalidationCompleted failed: Max attempts exceeded
Exited with code 255
```

**Comment by bqbn** [comment]
The failure is because the `aws cloudfront wait invalidation-completed` [[1]](https://github.com/mozilla/extension-workshop/blob/master/.utils/circleci/invalidate-cloudfront-cache.sh#L15-L17) command timed out. 

The command polls every 20 seconds until a successful state has been reached. This will exit with a return code of 255 after 30 failed checks. Unfortunately, the maximum wait time is fixed and can't be adjusted using a command line parameter. 

Cloudfront invalidation logs show that all three invalidation attempts finished eventually. It just that they each took more than 10 minutes to finish.

**Comment by jufemaiz** [comment]
Is this actually resolved?

**Comment by ivanmartos** [comment]
any suggestions what to do with that?
