### ISSUE TITLE
Outside source links open in the same tab

### ISSUE THREAD

**Issue by vcarciu** [mozilla/extension-workshop#698]
Steps to reproduce:

1.Access https://extensionworkshop.allizom.org/. 
2.Click on any link that has the square symbol at the end or it’s intended to be opened in a new tab.

Expected result:
Page opens in a new tab.

Actual result:
Page opens in the same tab.

Notes:
Not reproducible on the Extensions Workshop Production site.
Reproduced on all such links from the Stage site.

Please see video for this issue : 
![Links open in same tab in stage and in prod some open in a new tab](https://user-images.githubusercontent.com/1583842/89310882-f6514a00-d67d-11ea-88b8-95b25b7c93e7.gif)

**Comment by muffinresearch** [comment]
Adding an equivalent to the jekyll plugin that previously did this to 11ty as a transform slowed down the build significantly so that wasn't done.

However, since it can be done via a PostHTML plugin as part of the production build if we feel it's necessary.  That would mean it's not present during development if done that way which is one downside. 

It would probably be a good idea to revisit if we actually need/want this. See https://css-tricks.com/use-target_blank/ for some thoughts on the subject.

The only reason I can see that it might be nice is from the perspective of cross-referencing other docs but aside from that I'm not sure why we'd need to change the default behaviour.

/cc @caitmuenster for thoughts.

**Comment by caitmuenster** [comment]
Thanks! This is a nice-to-have; I'm concerned about people getting lost when they click on links and are taken to an entirely new site. 

I'm not sure that I want that behavior on prod if it isn't also on dev; maybe we can leave this as it is until we hear more feedback indicating that it's needed and/or we find a way of implementing it without slowing down the build.

**Comment by vcarciu** [comment]
Verified as fixed : 
![ewnewtab](https://user-images.githubusercontent.com/1583842/89912968-db418580-dbfb-11ea-9d97-3998798e75f5.gif)
