### ISSUE TITLE
Tags results page discrepancies between Stage and Production

### ISSUE THREAD

**Issue by vcarciu** [mozilla/extension-workshop#710]
Steps to reproduce:

1.Access https://extensionworkshop.allizom.org/documentation/develop/create-an-appealing-listing/ and scroll down to the bottom of the page.
2.Click on the “publishing” tag and observe the new page.
3.Access https://www.extensionworkshop.com/documentation/develop/create-an-appealing-listing/ and scroll down to the bottom of the page.
4.Click on the “publishing” tag and observe the new page.

Expected result:
The number of results it’s the same between the two sites.

Actual result:
There is a difference in the number of results between the sites.

Notes:
The display between the Stage and Production sites is also slightly different, as in Stage the number of results is not shown in the title of the page and the URL location of a result is truncated.
Also depending on the tags and how they are written, the results may not be listed in the same order.
The same tags may be displayed on multiple pages of the site. The below document shows the different locations of those:
https://docs.google.com/spreadsheets/d/1HuPBVuUpUKXt-HVvFj01cuvH13Ef6mBSobjibCGGIa8/edit#gid=156616875

Please view video for this issue : 
![publishing tags results](https://user-images.githubusercontent.com/1583842/89393630-bccb1e00-d713-11ea-8bc2-ef0066f38396.gif)

**Comment by muffinresearch** [comment]
As noted via a conversation on Slack: 

The numbers of results will be different because 11ty is building tag pages based on everything that was tagged rather than at runtime via the current search.

The display of the links for the host is because 11ty doesn't know about it at build time. That could potentially be fixed. Or it could be removed from the search results so they're at least both consistent. The latter would be easier.

The number of results could probably be easily added. I'll take a look at that.

**Comment by muffinresearch** [comment]
I've split this out into a focused bug here: https://github.com/mozilla/extension-workshop/issues/713
